name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/simpletimeservice:${{ github.sha }} ./app
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/simpletimeservice:${{ github.sha }}

      - name: Deploy ECS with Terraform
        working-directory: ./terraform/ecs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init -backend-config=../../simpletimeservice.hcl
          terraform plan -var "docker_image=${{ secrets.DOCKERHUB_USERNAME }}/simpletimeservice:${{ github.sha }}" -var-file=tfvars/dev.tfvars
          terraform apply -auto-approve -var "docker_image=${{ secrets.DOCKERHUB_USERNAME }}/simpletimeservice:${{ github.sha }}" -var-file=tfvars/dev.tfvars